language: php
php:
  - 5.5
  - 5.4

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - cp ./tests/general.php.travis ./tests/configuration/local/general.php
    - mysql -e 'create database umiframework;'

script: phpunit --configuration tests/phpunit.xml .