language: php
php:
  - 5.5
  - 5.4

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
    - cp tests/local-config.php.travis tests/local/general.php

script: phpunit --configuration tests/phpunit.xml .